import {
  Palmtree,
  Mountain,
  Waves,
  Landmark,
  PawPrint,
  Droplets,
  Droplet,
  Trees,
  TreePine,
  TreePalm,
  Leaf,
  Coffee,
  Castle,
  Church,
  Anchor,
  Map,
  Sun,
  Snowflake,
  Compass,
  Route,
  Tent,
  Home,
  Paintbrush,
  Feather,
  Building2,
  Gem,
  HeartPulse,
  Heart,
  Users,
  Smile,
  Camera,
  Sunrise,
  Sunset,
  Fish,
  Shell,
  Ship,
  Bird,
  Wheat,
  Flame,
  Triangle,
  Layers,
  HelpCircle,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";

export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  palmtree: Palmtree,
  mountain: Mountain,
  waves: Waves,
  landmark: Landmark,
  "paw-print": PawPrint,
  droplets: Droplets,
  droplet: Droplet,
  trees: Trees,
  "tree-pine": TreePine,
  "tree-palm": TreePalm,
  leaf: Leaf,
  coffee: Coffee,
  castle: Castle,
  church: Church,
  anchor: Anchor,
  map: Map,
  sun: Sun,
  snowflake: Snowflake,
  compass: Compass,
  route: Route,
  tent: Tent,
  home: Home,
  paintbrush: Paintbrush,
  feather: Feather,
  "building-2": Building2,
  gem: Gem,
  "heart-pulse": HeartPulse,
  heart: Heart,
  users: Users,
  smile: Smile,
  camera: Camera,
  sunrise: Sunrise,
  sunset: Sunset,
  fish: Fish,
  shell: Shell,
  ship: Ship,
  bird: Bird,
  wheat: Wheat,
  flame: Flame,
  triangle: Triangle,
  layers: Layers,
};
